spring:
  boot:
    admin:
      client:
        url:
        - http://localhost:1111/
  datasource:
    username: root
    password: naren
    url: jdbc:mysql://localhost:3306/majorproject
  
  jpa:
    hibernate:
      ddl-auto: 
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        
server:
  port: 9090
  
# Application Messages (auth-service is the prefix)

auth-service:
  messages:
    userReg: User Created
    userRegErr: User Creation Failed
    login : Login Successful
    loginErr : Invalid credentials
    
